name: Update base setup

on:
  workflow_call:        # This makes it reusable
    inputs:
      limits:
        required: true
        type: string
      host_labels:
        required: false
        type: string

jobs:
  ansible:
    runs-on: ${{ inputs.host_labels || 'ubuntu-latest' }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Bootstrap localhost
        env:
          DOTFILE_PRIVATE_KEY: "${{ secrets.DOTFILE_KEY }}"
        run: |
          ansible-playbook -i localhost, -c local ./bootstrap-runner.yml

      - name: Run Code
        env:
          DOTFILE_PRIVATE_KEY: "${{ secrets.DOTFILE_KEY }}"
        run: |
          ansible-playbook \
            -i inventory/other \
            --limit "${{ inputs.limits }}" \
            base-setup.yml || true
          ansible-playbook \
            -i inventory/staging \
            --limit "${{ inputs.limits }}" \
            base-setup.yml || true
          ansible-playbook \
            -i inventory/dev \
            --limit "${{ inputs.limits }}" \
            base-setup.yml || true
